const assert = require('node:assert/strict')
const fs = require('node:fs'), os = require('node:os'), path = require('node:path')
const { execFileSync, spawnSync } = require('node:child_process')
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agentdeck-account-files-'))
const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })
git('init', '-q')
git('config', 'user.name', 'Fixture'); git('config', 'user.email', 'fixture@example.invalid')
for (const dir of ['tools', '.githooks', 'examples']) fs.mkdirSync(path.join(root, dir))
for (const file of ['tools/check-account-files.js', 'tools/check-account-secrets.js', '.githooks/pre-commit', '.gitignore']) {
    fs.copyFileSync(path.join(__dirname, '..', file), path.join(root, file))
}
git('config', 'core.hooksPath', '.githooks')
const write = (name, data) => fs.writeFileSync(path.join(root, name), JSON.stringify(data))
write('examples/accounts.example.json', { claude: [{ name: '', id: '', password: '' }], codex: [] })
git('add', '.')
git('commit', '-qm', 'Empty format accepted')
write('accounts.json', { claude: [{ id: 'fixture@example.invalid' }] })
assert.ok(git('check-ignore', 'accounts.json').trim())
git('add', '-f', 'accounts.json')
const commit = () => spawnSync('git', ['commit', '-qm', 'Must be rejected'], { cwd: root, encoding: 'utf8' })
assert.notEqual(commit().status, 0, 'forced private file must block the actual commit')
assert.ok(fs.existsSync(path.join(root, 'accounts.json')), 'private working file is preserved')
git('rm', '--cached', 'accounts.json')
write('examples/accounts.example.json', { claude: [{ id: 'fixture@example.invalid' }] })
git('add', 'examples/accounts.example.json')
write('examples/accounts.example.json', { claude: [{ id: '' }] })
assert.notEqual(commit().status, 0, 'nonempty index must fail even after working file is cleaned')
git('add', 'examples/accounts.example.json')
git('commit', '-qm', 'Empty format accepted again')
// List-only checks must not follow native credential stores belonging to sessions.
const { collectLocalAccountSecrets } = require('../tools/check-account-secrets')
const list = path.join(root, 'accounts.json')
assert.equal(collectLocalAccountSecrets([list], [], false).accountCount, 1)
console.log('PASS: empty format commits; forced private file and populated staged example block actual commits; local file preserved.')
