const assert = require('node:assert/strict')
const { SessionIdentities, jobAliasBase, adaptiveAliasBase } = require('../.tmp/sessionIdentity')
const projects = []
assert.equal(adaptiveAliasBase('PowerShell', 'C:/Windows/System32', projects), '')
assert.equal(adaptiveAliasBase('', '', projects), '')
assert.equal(adaptiveAliasBase('어뷰징 수정', 'D:/Project/SampleGame/Root', projects), 'SampleGame')
assert.equal(adaptiveAliasBase('전투 수정', 'D:/Project/SampleGame/Global/Root', projects), 'SampleGame글로벌')
assert.equal(adaptiveAliasBase('전투 수정', 'D:/Project/SampleGame/China/Root', projects), 'SampleGame중국')
assert.equal(adaptiveAliasBase('글로벌 전투 수정', 'D:/Project/SampleGame/Root', projects), 'SampleGame글로벌')
assert.equal(adaptiveAliasBase('전투 수정', 'D:/Project/ProjectBeta/Root', projects), 'ProjectBeta')
assert.equal(adaptiveAliasBase('예제베타 프로젝트 개발', 'D:/Project/ProjectBeta/Root', projects), '예제베타')
assert.equal(adaptiveAliasBase('전투 수정', 'D:/Project/ProjectBeta/Root', JSON.parse(JSON.stringify(projects))), '예제베타')
assert.equal(adaptiveAliasBase('예제감마 프로젝트 개발', 'D:/Project/ProjectGamma/src', projects), '예제감마')
assert.equal(adaptiveAliasBase('전투 수정', 'D:/Project/UnseenGame/Root', projects), 'UnseenGame')
assert.equal(adaptiveAliasBase('신규 프로젝트 개발', 'D:/Project/UnseenGame/Root', projects), 'UnseenGame')
assert.equal(adaptiveAliasBase('다른이름 프로젝트 개발', 'D:/Project/ProjectBeta/Root', projects), '예제베타')
assert.equal(adaptiveAliasBase('탭 통신 개선', 'D:/Project/ProjectBeta/Root', projects), '에이전트덱')
assert.equal(adaptiveAliasBase('작업', 'D:/Project/SampleGame/Root', projects), 'SampleGame')
const stable = new SessionIdentities([])
const oldName = stable.ensure('old', '게임').alias
stable.ensure('old', adaptiveAliasBase('작업', 'D:/Project/SampleGame/China/Root', projects))
assert.equal(stable.records[0].alias, oldName)
const records = []
let registry = new SessionIdentities(records)
assert.equal(jobAliasBase('탭 통신 번호 고정 개선 검토', 'D:/Project/SampleGame/Root'), '에이전트덱')
assert.equal(jobAliasBase('허브 작업 관련규칙', 'D:/Project/SampleGame/Root'), '허브')
assert.equal(jobAliasBase('어뷰징 제재 설정 정리', ''), '게임')
assert.equal(jobAliasBase('sl-infra를 my-infra로 이름 변경', ''), '인프라')
assert.equal(jobAliasBase('메인세션 모델 설정 토큰 효율성', ''), '도구')
assert.equal(jobAliasBase('PowerShell', 'D:/Project/SampleGame/Root'), 'SampleGame')
assert.equal(jobAliasBase('개발 진행', 'D:/Project/Widget/src'), 'Widget')
assert.equal(registry.ensure('first', '에이전트덱').alias, '에이전트덱1')
assert.equal(registry.ensure('second', '에이전트덱').alias, '에이전트덱2')
assert.equal(registry.ensure('third', '게임').alias, '게임1')
assert.equal(registry.ensure('first', '허브').alias, '에이전트덱1')
registry = new SessionIdentities(JSON.parse(JSON.stringify(records)))
assert.deepEqual(registry.ensure('first'), { id: 'first', letter: '', alias: '에이전트덱1' })
assert.equal(registry.ensure('replacement', '에이전트덱').alias, '에이전트덱3')
for (let i = 0; i < 1000; i++) registry.ensure(`extra-${i}`, '게임')
assert.equal(new Set(registry.records.map(x => x.alias)).size, registry.records.length)
const migrated = new SessionIdentities([{id:'old',letter:'C',alias:''},{id:'named',letter:'A',alias:'허브1'}])
assert.equal(migrated.ensure('old','허브').alias, '허브2')
assert.equal(migrated.ensure('named','게임').alias, '허브1')
console.log('PASS: job-related automatic names, immutable aliases, 1000+ unique names, persisted reservations and migration')
