const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { SessionMailbox } = require('../.tmp/sessionMailbox')
const { SessionSlots } = require('../.tmp/sessionSlots')
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'agentdeck-mailbox-test-'))
const file = path.join(dir, 'mailbox.json')
const slots = new SessionSlots()
slots.reconcile(['a', 'b', 'c'])
slots.reconcile(['c', 'a'])
assert.equal(slots.get(1), 'a')
assert.equal(slots.get(2), null)
assert.equal(slots.get(3), 'c')
slots.reconcile(['c', 'a', 'd'])
assert.equal(slots.get(2), 'd')
slots.reconcile(Array.from({ length: 12 }, (_, i) => String(i)))
assert.equal(slots.full, true)
assert.equal(slots.get(10), null)
let mailbox = new SessionMailbox(file)
const a = mailbox.register('session-a', 'A', '/work')
const b = mailbox.register('session-b', 'B', '/work')
const call = (actor, method, args) => mailbox.call(actor.sessionId, actor.token, method, args)
const request = { toSessionId: b.sessionId, body: 'Review this change', requestKey: 'review-1' }
const rename = fs.renameSync
try {
    fs.renameSync = () => { throw new Error('simulated disk failure') }
    assert.throws(() => call(a, 'send', request), /disk failure/)
    assert.equal(call(b, 'receive').length, 0)
} finally { fs.renameSync = rename }
const sent = call(a, 'send', request)
assert.equal(call(a, 'send', request).id, sent.id)
assert.throws(() => call(a, 'send', { ...request, body: 'different' }))
assert.equal(call(b, 'receive')[0].id, sent.id)
assert.throws(() => call(a, 'acknowledge', { messageId: sent.id }))
assert.throws(() => mailbox.call(a.sessionId, b.token, 'receive'))
assert.throws(() => call(a, 'send', { slot: 2, body: 'bad', requestKey: 'bad' }))
assert.throws(() => call(a, 'send', { ...request, toSessionId: 2 }))
assert.ok(call(b, 'acknowledge', { messageId: sent.id }).readAt)
const reply = call(b, 'send', { toSessionId: a.sessionId, body: 'Reviewed', requestKey: 'reply-1', replyTo: sent.id })
assert.equal(reply.replyTo, sent.id)
call(b, 'acknowledge', { messageId: sent.id, completed: true })
assert.equal(call(b, 'receive').length, 0)
mailbox = new SessionMailbox(file)
assert.throws(() => call(a, 'receive'))
assert.equal(mailbox.register(a.sessionId, 'A', '/work').token, a.token)
mailbox.register(b.sessionId, 'B', '/work')
assert.equal(call(a, 'receive')[0].id, reply.id)
assert.equal(call(b, 'receive').length, 0)
mailbox.close(b.sessionId)
assert.throws(() => call(a, 'send', { ...request, requestKey: 'after-close' }))
mailbox.register('replacement-session', 'new session in same UI slot', '/work')
assert.throws(() => call(a, 'send', { ...request, requestKey: 'after-reuse' }))
assert.equal(JSON.parse(fs.readFileSync(file)).messages.length, 2)
fs.rmSync(dir, { recursive: true })
console.log('PASS: fixed slots, authenticated send/receive/reply, idempotency, acknowledgements, disk restart, closed recipients and slot reuse isolation')
