const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { SessionMailbox } = require('../.tmp/sessionMailbox')
const { SessionSlots } = require('../.tmp/sessionSlots')
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'agentdeck-mailbox-test-'))
const file = path.join(dir, 'mailbox.json')
const slots = new SessionSlots()
slots.reconcile(['a', 'b', 'c'])
slots.reconcile(['c', 'a'])
assert.equal(slots.get(1), 'a')
assert.equal(slots.get(2), null)
assert.equal(slots.get(3), 'c')
slots.reconcile(['c', 'a', 'd'])
assert.equal(slots.get(2), 'd')
slots.reconcile(Array.from({ length: 12 }, (_, i) => String(i)))
assert.equal(slots.full, true)
assert.equal(slots.get(10), null)
let mailbox = new SessionMailbox(file)
const a = mailbox.register('session-a', 'A', '/work')
const b = mailbox.register('session-b', 'B', '/work')
const call = (actor, method, args) => mailbox.call(actor.sessionId, actor.token, method, args)
const request = { toSessionId: b.sessionId, body: 'Review this change', requestKey: 'review-1' }
const rename = fs.renameSync
try {
    fs.renameSync = () => { throw new Error('simulated disk failure') }
    assert.throws(() => call(a, 'send', request), /disk failure/)
    assert.equal(call(b, 'receive').length, 0)
} finally { fs.renameSync = rename }
const sent = call(a, 'send', request)
assert.equal(call(a, 'send', request).id, sent.id)
assert.throws(() => call(a, 'send', { ...request, body: 'different' }))
assert.equal(call(b, 'receive')[0].id, sent.id)
assert.throws(() => call(a, 'acknowledge', { messageId: sent.id }))
assert.throws(() => mailbox.call(a.sessionId, b.token, 'receive'))
assert.throws(() => call(a, 'send', { slot: 2, body: 'bad', requestKey: 'bad' }))
assert.throws(() => call(a, 'send', { ...request, toSessionId: 2 }))
assert.ok(call(b, 'acknowledge', { messageId: sent.id }).readAt)
const reply = call(b, 'send', { toSessionId: a.sessionId, body: 'Reviewed', requestKey: 'reply-1', replyTo: sent.id })
assert.equal(reply.replyTo, sent.id)
call(b, 'acknowledge', { messageId: sent.id, completed: true })
assert.equal(call(b, 'receive').length, 0)
mailbox = new SessionMailbox(file)
assert.throws(() => call(a, 'receive'))
assert.equal(mailbox.register(a.sessionId, 'A', '/work').token, a.token)
mailbox.register(b.sessionId, 'B', '/work')
assert.equal(call(a, 'receive')[0].id, reply.id)
assert.equal(call(b, 'receive').length, 0)
mailbox.close(b.sessionId)
assert.equal(call(a, 'send', { ...request, requestKey: 'after-close' }).wake.reason, 'no-tab')
mailbox.register('replacement-session', 'new session in same UI slot', '/work')
assert.equal(call(a, 'send', { ...request, requestKey: 'after-reuse' }).wake.reason, 'no-tab')
assert.equal(call({ ...a, ...mailbox.register('replacement-session', 'new', '/work') }, 'receive').length, 0)
assert.equal(JSON.parse(fs.readFileSync(file)).messages.length, 4)
// Reply routing and hook-only delivery must hold even when terminal wake is enabled.
const replyFile = path.join(dir, 'replies.json')
let wakeCalls = 0
const wake = () => { wakeCalls++; return { attempted: true, delivered: true, reason: 'sent' } }
let replies = new SessionMailbox(replyFile, wake)
const sender = replies.register('sender', '', '/work')
const receiver = replies.register('receiver', '', '/work')
const stranger = replies.register('stranger', '', '/work')
const replyCall = (actor, method, args) => replies.call(actor.sessionId, actor.token, method, args)
const original = replyCall(sender, 'send', { toSessionId: receiver.sessionId, body: 'hello', requestKey: 'hello' })
assert.equal(wakeCalls, 1)
const answerArgs = { messageId: original.id, body: '안녕하세요', requestKey: 'answer' }
assert.throws(() => replyCall(stranger, 'reply', answerArgs), /not found/)
assert.throws(() => replyCall(sender, 'reply', answerArgs), /not found/)
assert.throws(() => replyCall(receiver, 'reply', { ...answerArgs, toSessionId: stranger.sessionId }), /Unknown/)
assert.throws(() => replyCall(receiver, 'reply', { ...answerArgs, messageId: 'missing' }), /not found/)
assert.throws(() => replyCall(receiver, 'reply', { ...answerArgs, body: ' ' }), /Provide/)
try {
    fs.renameSync = () => { throw new Error('simulated reply disk failure') }
    assert.throws(() => replyCall(receiver, 'reply', answerArgs), /disk failure/)
    assert.equal(replyCall(sender, 'receive').length, 0)
} finally { fs.renameSync = rename }
const answer = replyCall(receiver, 'reply', answerArgs)
assert.equal(answer.toSessionId, sender.sessionId)
assert.equal(answer.replyTo, original.id)
assert.deepEqual(answer.wake, { attempted: false, delivered: false, reason: 'reply-queued' })
assert.equal(replyCall(sender, 'receive')[0].body, answerArgs.body)
assert.equal(replyCall(receiver, 'receive')[0].completedAt, undefined)
assert.equal(replyCall(receiver, 'reply', answerArgs).id, answer.id)
assert.throws(() => replyCall(receiver, 'reply', { ...answerArgs, body: 'changed' }), /requestKey/)
assert.equal(JSON.parse(fs.readFileSync(replyFile)).messages.length, 2)
replies = new SessionMailbox(replyFile, wake)
replies.register(receiver.sessionId, '', '/work')
// An offline sender's exact session retains its reply until its next registration/hook.
const offline = replyCall(receiver, 'reply', { ...answerArgs, requestKey: 'offline' })
assert.equal(offline.toSessionId, sender.sessionId)
replies.register(sender.sessionId, '', '/work')
assert.equal(replyCall(sender, 'receive')[0].id, answer.id)
assert.equal(replyCall(sender, 'receive')[1].id, offline.id)
assert.equal(replyCall(receiver, 'reply', answerArgs).id, answer.id)
replyCall(receiver, 'acknowledge', { messageId: original.id, completed: true })
assert.equal(replyCall(receiver, 'reply', { ...answerArgs, requestKey: 'later' }).replyTo, original.id)
const legacy = replyCall(receiver, 'send', { toSessionId: sender.sessionId, body: 'legacy', requestKey: 'legacy', replyTo: original.id })
assert.equal(legacy.wake.reason, 'reply-queued')
assert.equal(wakeCalls, 1, 'replies and retries must never invoke terminal wake')
// No pane, hook registration, or pre-created server credential for an external peer.
const externalToken = 'ab'.repeat(32)
const externalRequest = { toSessionId: receiver.sessionId, body: 'external first', requestKey: 'external-first' }
assert.throws(() => replies.callExternal('external', externalToken, 'receive'), /first message/)
assert.throws(() => replies.callExternal('external', externalToken, 'send', { ...externalRequest, body: '' }), /Provide/)
assert.equal(replyCall(receiver, 'sessions').some(x => x.sessionId === 'external'), false)
assert.throws(() => replies.callExternal(receiver.sessionId, externalToken, 'send', externalRequest), /credentials/)
const externalFirst = replies.callExternal('external', externalToken, 'send', externalRequest)
assert.equal(replyCall(receiver, 'receive').find(x => x.id === externalFirst.id).fromSessionId, 'external')
const externalAnswer = replyCall(receiver, 'reply', { messageId: externalFirst.id, body: 'external answer', requestKey: 'external-answer' })
assert.equal(replies.callExternal('external', externalToken, 'receive')[0].id, externalAnswer.id)
assert.equal(replies.callExternal('external', externalToken, 'send', externalRequest).id, externalFirst.id)
assert.throws(() => replies.callExternal('external', 'cd'.repeat(32), 'receive'), /credentials/)
replies = new SessionMailbox(replyFile, wake)
assert.equal(replies.callExternal('external', externalToken, 'receive')[0].id, externalAnswer.id)
assert.equal(replies.callExternal('external', externalToken, 'acknowledge', { messageId: externalAnswer.id, completed: true }).completedAt > 0, true)
assert.equal(replies.callExternal('external', externalToken, 'receive').length, 0)
assert.equal(JSON.parse(fs.readFileSync(replyFile)).messages.filter(x => x.id === externalFirst.id).length, 1)
fs.rmSync(dir, { recursive: true })
console.log('PASS: fixed slots, authenticated send/receive/reply, idempotency, acknowledgements, disk restart, closed recipients and slot reuse isolation')
