const assert = require('node:assert/strict')
const fs = require('node:fs'), os = require('node:os'), path = require('node:path')
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agentdeck-storage-'))
process.env.AGENTDECK_ACCOUNTS_FILE = path.join(root, 'old', 'custom-accounts.json')
process.env.CLAUDE_CONFIG_DIR = path.join(root, 'old-claude')
process.env.CODEX_HOME = path.join(root, 'old-codex')
const paths = require('../.tmp/storagePaths')
const accounts = require('../.tmp/accounts')
const blank = { accountStorageDir: '', claudeStorageDir: '', codexStorageDir: '' }
assert.equal(paths.accountsFile(), process.env.AGENTDECK_ACCOUNTS_FILE)
assert.equal(paths.agentHome('claude'), process.env.CLAUDE_CONFIG_DIR)
const draft = { accountStorageDir: path.join(root, 'accounts-new'),
    claudeStorageDir: path.join(root, 'claude-new'), codexStorageDir: path.join(root, 'codex-new') }
assert.deepEqual(paths.validateStoragePaths(draft), draft)
assert.ok(!fs.existsSync(draft.accountStorageDir), 'Validation does not create folders')
assert.throws(() => paths.validateStoragePaths({ ...draft, accountStorageDir: 'relative' }), /absolute/)
assert.throws(() => paths.validateStoragePaths({ ...draft, codexStorageDir: draft.claudeStorageDir }), /separate/)
assert.throws(() => paths.validateStoragePaths({ ...draft, codexStorageDir: path.join(draft.claudeStorageDir, 'child') }), /separate/)
fs.writeFileSync(path.join(root, 'file'), 'keep')
assert.throws(() => paths.validateStoragePaths({ ...draft, accountStorageDir: path.join(root, 'file', 'child') }), /directory/)
paths.configureStoragePaths(draft)
draft.accountStorageDir = 'mutated-after-startup'
assert.equal(paths.accountsFile(), path.join(root, 'accounts-new', 'accounts.json'), 'Startup snapshot is stable')
accounts.addAccount('claude', 'fixture@example.invalid', 'synthetic-password')
const account = accounts.readAccounts()[0]
assert.equal(accounts.accountHome(account), path.join(root, 'accounts-new', 'accounts', account.key))
accounts.prepareAccount(account)
const history = path.join(accounts.accountHome(account), 'projects')
assert.equal(fs.realpathSync(history), fs.realpathSync(path.join(root, 'claude-new', 'projects')))
fs.writeFileSync(path.join(history, 'synthetic.jsonl'), 'fixture')
assert.equal(fs.readFileSync(path.join(root, 'claude-new', 'projects', 'synthetic.jsonl'), 'utf8'), 'fixture')
assert.equal(accounts.accountEnv(account).CLAUDE_CONFIG_DIR, accounts.accountHome(account))
accounts.addAccount('codex', 'codex-fixture@example.invalid', 'synthetic-password')
const codex = accounts.readAccounts().find(a => a.provider === 'codex')
accounts.prepareAccount(codex)
for (const name of ['sessions', 'archived_sessions']) {
    const target = path.join(accounts.accountHome(codex), name)
    assert.equal(fs.realpathSync(target), fs.realpathSync(path.join(root, 'codex-new', name)))
    fs.writeFileSync(path.join(target, 'fixture.jsonl'), 'codex-fixture')
    assert.equal(fs.readFileSync(path.join(root, 'codex-new', name, 'fixture.jsonl'), 'utf8'), 'codex-fixture')
}
assert.equal(accounts.accountEnv(codex).CODEX_HOME, accounts.accountHome(codex))
assert.notEqual(accounts.accountHome(account), accounts.accountHome(codex))
assert.equal(paths.storageEnvironment().CODEX_HOME, path.join(root, 'codex-new'))
assert.equal(paths.storageEnvironment({ CODEX_HOME: 'explicit-profile' }).CODEX_HOME, 'explicit-profile')
paths.configureStoragePaths({ ...blank, accountStorageDir: path.join(root, 'accounts-new'), claudeStorageDir: path.join(root, 'claude-next') })
accounts.prepareAccount(account)
assert.equal(fs.realpathSync(history), fs.realpathSync(path.join(root, 'claude-next', 'projects')))
assert.equal(fs.readFileSync(path.join(root, 'claude-new', 'projects', 'synthetic.jsonl'), 'utf8'), 'fixture', 'Old history remains intact')
paths.configureStoragePaths(blank)
assert.equal(paths.accountsFile(), process.env.AGENTDECK_ACCOUNTS_FILE)
assert.ok(!fs.existsSync(paths.accountsFile()), 'Old location was never written')
console.log('PASS: storage defaults, validation, restart snapshot, account routing, history writes, link switching, original preservation, explicit profile precedence')
